// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/shunsukenagashima/chat-api/pkg/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// RoomRepository is an autogenerated mock type for the RoomRepository type
type RoomRepository struct {
	mock.Mock
}

// CreateAndAddUser provides a mock function with given fields: ctx, room, ownerId
func (_m *RoomRepository) CreateAndAddUser(ctx context.Context, room *model.Room, ownerId string) error {
	ret := _m.Called(ctx, room, ownerId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Room, string) error); ok {
		r0 = rf(ctx, room, ownerId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, roomId
func (_m *RoomRepository) Delete(ctx context.Context, roomId string) error {
	ret := _m.Called(ctx, roomId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, roomId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllPublic provides a mock function with given fields: ctx
func (_m *RoomRepository) GetAllPublic(ctx context.Context) ([]*model.Room, error) {
	ret := _m.Called(ctx)

	var r0 []*model.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Room, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Room); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, roomId
func (_m *RoomRepository) GetById(ctx context.Context, roomId string) (*model.Room, error) {
	ret := _m.Called(ctx, roomId)

	var r0 *model.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Room, error)); ok {
		return rf(ctx, roomId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Room); ok {
		r0 = rf(ctx, roomId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roomId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *RoomRepository) GetByName(ctx context.Context, name string) (*model.Room, error) {
	ret := _m.Called(ctx, name)

	var r0 *model.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Room, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Room); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, room
func (_m *RoomRepository) Update(ctx context.Context, room *model.Room) error {
	ret := _m.Called(ctx, room)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Room) error); ok {
		r0 = rf(ctx, room)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRoomRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRoomRepository creates a new instance of RoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRoomRepository(t mockConstructorTestingTNewRoomRepository) *RoomRepository {
	mock := &RoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
